web/acceptor/urls.py
"""
Acceptor URL Configuration.
"""

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [  # pylint: disable=invalid-name
    url(r'^admin/', admin.site.urls),
    url(r'^', include('olga.charts.urls')),
    url(r'^', include('olga.analytics.urls')),
]

web/olga/charts/urls.py
"""
URLs for the charts application.
"""

from django.conf.urls import url

from . import views

app_name = 'charts'

urlpatterns = [
    url(r'^$', views.GraphsView.as_view(), name='charts'),
    url(r'^map/$', views.MapView.as_view(), name='map')
]

web/olga/charts/models.py
"""
Models for charts application.
"""

web/olga/charts/views.py
"""
Views for the charts application.
"""

import json
from datetime import datetime

from django.shortcuts import render
from django.views.generic import View
from django.db.models import Max, Min

from olga.analytics.models import InstallationStatistics


def get_data_created_datetime_scope():
    """
    Get the first and last datetimes for the entire time of gathering statistics.
    """
    data_created_datetime_scope = InstallationStatistics.objects.aggregate(
        Min('data_created_datetime'), Max('data_created_datetime')
    )

    first_dt = data_created_datetime_scope['data_created_datetime__min'] or datetime.now()
    last_dt = data_created_datetime_scope['data_created_datetime__max'] or datetime.now()

    return first_dt, last_dt


class MapView(View):
    """
    Display information on a world map and tabular view.
    """

    @staticmethod
    def get(request):
        """
        Pass graph data to frontend.
        """
        first_datetime_of_update_data, last_datetime_of_update_data = get_data_created_datetime_scope()

        context = {
            'months': json.dumps(InstallationStatistics().get_students_per_country()),
            'first_datetime_of_update_data': first_datetime_of_update_data,
            'last_datetime_of_update_data': last_datetime_of_update_data,
        }
        return render(request, 'charts/worldmap.html', context)


class GraphsView(View):
    """
    Provide data and plot 3 main graphs: number of, students, courses and instances per date.
    """

    @staticmethod
    def get(request):
        """
        Pass graph data to frontend.
        """
        timeline = InstallationStatistics.timeline()

        students, courses, instances = InstallationStatistics.data_per_period()

        first_datetime_of_update_data, last_datetime_of_update_data = get_data_created_datetime_scope()

        charts = InstallationStatistics.get_charts_data()

        context = {
            'timeline': json.dumps(timeline),
            'students': json.dumps(students),
            'courses': json.dumps(courses),
            'instances': json.dumps(instances),
            'first_datetime_of_update_data': first_datetime_of_update_data,
            'last_datetime_of_update_data': last_datetime_of_update_data,
            'charts': json.dumps(charts),
        }

        # Update context with this data: instances_count, courses_count, students_count, generated_certificates_count
        context.update(InstallationStatistics.overall_counts())

        return render(request, 'charts/graphs.html', context)

web/olga/charts/templates/charts/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OpenedX Learners Global Analytics | OLGA</title>
    <link rel="stylesheet" type="text/css" href="{% static 'charts/vendored/edx_front_styles.css' %}" />
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>

    {% block head %}
    {% endblock %}
</head>

<body class="view-course-engagement view-dashboard" data-gr-c-s-loaded="true">
    <header class="navbar navbar-default" id="nav">
        <div class="grid-container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav" role="tab"
                        aria-selected="false" aria-expanded="false" id="ui-collapse-671">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="/" data-track-type="click" data-track-event="edx.bi.ui.menu.navigated"
                   data-track-url="/" data-track-target-scope="insights" data-track-target-lens="home"
                   data-track-menu-depth="home" data-track-link-name="logo">
                    <div class="navbar-brand-logo" alt="demo"></div>
                </a>

                <ul class="nav navbar-nav">
                    <li><a href="#" id="olga-dates" class="navbar-link active-course-name">Open edX Learners Global Analytics for {{ first_datetime_of_update_data|date:"Y-m" }} — {{ last_datetime_of_update_data|date:"Y-m" }}</a></li>
                </ul>
            </div>
            <!-- / navbar-collapse -->
        </div>
        <!-- / container -->
    </header>
    <!-- / navbar -->

    {% block body %}
    {% endblock %}

    {#FOOTER#}
    <div id="footer-sock">
        <footer class="footer" aria-label="Application">
            <div class="feedback">
                <div class="grid-container grid-manual">
                    <div class="row">
                        <div class="col col-12">
                            This information is gathered in anonymous manner from volunteered Open edX instances.
                            Thanks a lot for participation! <br/>Want to be a part of this?
                            <a class="support-email" href="mailto:info@raccoongang.com?Subject=Participation">
                                Contact OLGA team</a>.<br/>Comments or suggestions? Email
                            <a class="feedback-email" href="mailto:info@raccoongang.com?Subject=Feedback">info@raccoongang.com</a>.
                        </div>
                    </div>
                </div>
            </div>

            <div class="legal">
                <div class="grid-container grid-manual">
                    <div class="row">
                        <div id="footer-text" class="col col-12 sm-col-12 md-col-6 text-right">
                            <p class="copyright">by <a href="https://raccoongang.com/">Raccoon Gang</a>, 2018</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    {% block footer %}
    {% endblock %}

    {% block script %}
    {% endblock %}

</body>
</html>

web/olga/charts/templates/charts/graphs.html
{% extends 'charts/base.html' %}
{% load static %}
{% block head %}
    <script src="https://cdn.plot.ly/plotly-1.27.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <link rel="stylesheet" href="{% static 'charts/edits.css' %}">
{% endblock %}

{% block body %}
    <script>
        // Define JS global vars to work with external graph.js file.
        var timeline = JSON.parse('{{ timeline|safe }}');
        var students = JSON.parse('{{ students|safe }}');
        var courses = JSON.parse('{{ courses|safe }}');
        var instances = JSON.parse('{{ instances|safe }}');
        var newData = {
            'total_registered_students': {{ registered_students_count|safe }},
            'total_generated_certificates': {{ generated_certificates_count|safe }},
            'monthly': {{ charts|safe }}
        }
    </script>

<div id="wrap-content-push-footer-sock">
    <a id="skip" href="#content" class="skip-link">Skip to content</a>

        {#NAVBAR#}
        <nav class="navbar navbar-default lens-nav" role="navigation" aria-label="Application">
            <div class="grid-container">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <button class="dropdown-toggle navbar-link" data-toggle="dropdown" id="lensPrimaryMenu"
                                aria-controls="lensDropdownMenu" aria-haspopup="true" aria-expanded="false">

                            <span class="link-label">
                                Engagement
                            </span>
                        </button>
                    </li>

                    <li class="active nav-section">
                        <a href="{% url 'charts:charts' %}" data-track-type="click"
                           data-track-event="edx.bi.ui.menu.navigated" data-track-text="Content"
                           data-track-url="#" data-track-target-scope="course" data-track-target-lens="engagement"
                           data-track-target-report="content" data-track-target-depth="" data-track-menu-depth="report"
                           data-track-link-name="content">

                            <span class="link-label">
                                Numbers <span class="sr-only">(Active)</span>
                            </span>
                        </a>
                    </li>

                    <li class=" nav-section">
                        <a href="{% url 'charts:map' %}" data-track-type="click"
                           data-track-event="edx.bi.ui.menu.navigated" data-track-text="Videos"
                           data-track-url="#"
                           data-track-target-scope="course" data-track-target-lens="engagement"
                           data-track-target-report="videos" data-track-target-depth=""
                           data-track-menu-depth="report" data-track-link-name="videos">

                            <span class="link-label">Geography</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="grid-container grid-manual">
            <div class="row">
                <main class="col col-12 sm-col-12 main" id="content" aria-label="Application">
                    <div class="view-head"></div>
                        <div class="view-intro row">
                        <p class="lead text-muted intro-text"></p>
                    </div>

                    {#METRICS#}
                    <section class="view-section">
                        <div class="section-heading bordered">
                            <h4 class="section-title">Global Activity Metrics</h4>
                        </div>
                        <div class="row">
                            <div class="col col-12 sm-col-12 md-col-2" data-activity-type="any">
                                <div class="summary-point text-center">
                                    <div class="summary-point-wrapper"><div class="summary-point-number" title="{{ instances_count }}">{{ instances_count }}</div><div class="summary-point-label">Instances</div></div>
                                </div>
                            </div>
                            <div class="col col-12 sm-col-12 md-col-2" data-activity-type="any">
                                <div class="summary-point text-center">
                                    <div class="summary-point-wrapper"><div class="summary-point-number" title="{{ courses_count }}">{{ courses_count }}</div><div class="summary-point-label">Courses</div></div>
                                </div>
                            </div>
                            <div class="col col-12 sm-col-12 md-col-2" data-activity-type="any">
                                <div class="summary-point text-center">
                                    <div class="summary-point-wrapper"><div class="summary-point-number" title="{{ students_count }}">{{ students_count }}</div><div class="summary-point-label">Active Students</div></div>
                                </div>
                            </div>
                            <div class="col col-12 sm-col-12 md-col-3" data-activity-type="any">
                                <div class="summary-point text-center">
                                    <div class="summary-point-wrapper"><div class="summary-point-number" title="{{ total_generated_certificates }}" id="js-total-cert">{{ total_generated_certificates }}</div><div class="summary-point-label">Certificates</div></div>
                                </div>
                            </div>
                            <div class="col col-12 sm-col-12 md-col-3" data-activity-type="any">
                                <div class="summary-point text-center">
                                    <div class="summary-point-wrapper"><div class="summary-point-number" title="{{ total_registered_students }}" id="js-total-stud">{{ total_registered_students }}</div><div class="summary-point-label">Total Registered Students</div></div>
                                </div>
                            </div>
                        </div>
                    </section>

                    {#CHARTS#}
                    <section class="view-section" aria-hidden="true">
                        <div class="section-heading">
                          <h4 class="section-title">Global Learners Engagement</h4>
                          <span class="section-heading-note small">
                              How many learners are interacting with Open edX courses?
                          </span>
                        </div>
                        <div class="section-content section-data-graph">
                            <div class="section-content section-data-viz">
                                <div class="analytics-chart-container">
                                    <div>
                                        <p class="tooltip-unzoom">To zoom/unzoom plot - double click on it</p>
                                        <div>
                                            <div id="instances"></div>
                                            <div id="courses"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    {#UPDATE TIME#}

                    <div class="data-update-message">Course engagement data was last updated
                        {{ last_datetime_of_update_data|date:"Y-m-d" }} at {{ last_datetime_of_update_data|date:"H:i" }} UTC+2.
                    </div>
                </main>
            </div>
        </div>

    <!-- Placed at the end of the document so the pages load faster -->
    <div id="footer-sock-push"></div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block script %}
    <script src="{% static 'charts/graphs.js' %}"></script>
{% endblock %} }}

web/olga/charts/templates/charts/worldmap.html
{% extends 'charts/base.html' %}
{% load static %}
{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <link rel="stylesheet" href="{% static 'charts/edits.css' %}">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'charts/slider.css' %}">
{% endblock %}

{% block body %}
<div id="wrap-content-push-footer-sock">
    <a id="skip" href="#content" class="skip-link">Skip to content</a>

    {#NAVBAR#}
    <nav class="navbar navbar-default lens-nav" role="navigation" aria-label="Application">
        <div class="grid-container">
              <ul class="nav navbar-nav">
                    <li class="dropdown">
                          <button class="dropdown-toggle navbar-link" data-toggle="dropdown" id="lensPrimaryMenu"
                                  aria-controls="lensDropdownMenu" aria-haspopup="true" aria-expanded="false">
                                <span class="link-label">
                                  Engagement
                                </span>
                          </button>
                    </li>
                    <li class=" nav-section">
                        <a href="{% url 'charts:charts' %}">
                            <span class="link-label">Numbers</span>
                        </a>
                    </li>
                    <li class="active nav-section">
                        <a href="{% url 'charts:map' %}" >
                            <span class="link-label">Geography
                                <span class="sr-only">(Active)</span>
                            </span>
                        </a>
                    </li>
              </ul>
        </div>
    </nav>

    <div class="grid-container grid-manual">
        <div class="row">
            <main class="col col-12 sm-col-12 main" id="content" aria-label="Application">
                <div class="view-head"></div>
                <div class="view-intro row"><p class="lead text-muted intro-text"></p></div>

                {#METRICS#}
                <section class="view-section">
                    <div class="section-heading bordered"><h4 class="section-title">
                        Global Activity Metrics</h4>
                    </div>

                    <div class="row">
                        <div class="col col-12 sm-col-12 md-col-6" data-activity-type="any">
                            <div class="summary-point text-center">
                                <div class="summary-point-wrapper"><div class="summary-point-number" title="" id="top_country"></div><div class="summary-point-label">Top Country by Enrollment</div></div>
                            </div>
                        </div>

                        <div class="col col-12 sm-col-12 md-col-6" data-activity-type="any">
                            <div class="summary-point text-center">
                                <div class="summary-point-wrapper"><div class="summary-point-number" title="" id="countries_amount"></div><div class="summary-point-label">Countries in Statistics</div></div>
                            </div>
                        </div>
                    </div>
                </section>

                {#FILTER#}
                <section class="view-section">
                    <div class="row">
                        <div class="slider-wrapper">
                            <div id="slider">
                                <div id="custom-handle" class="ui-slider-handle"></div>
                            </div>
                        </div>
                        <div class="slider-button">
                            <input type="button" value="Play retrospective" id="play_retrospective" class="btn btn-default">
                        </div>
                    </div>
                </section>
                {#FILTER#}

                <section class="view-section" aria-hidden="false">
                    <div class="section-heading">
                        <h4 class="section-title">Global Learners Engagement</h4>
                        <span class="section-heading-note small">Where are our learners?</span>
                    </div>

                    <div class="section-content section-data-graph">
                        <div class="section-content section-data-viz">
                            <div class="analytics-chart-container">
                                <div style="display: flex; height: 550px;align-items: center;justify-content: center;">
                                    <div id="datamap-container"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {#TABLES#}
                <section class="view-section">
                    <div class="section-heading">
                        <h4 class="section-title">Geographic Breakdown</h4>
                    </div>

                    <div class="section-content section-data-table" data-role="enrollment-location-table">
                        <div class="table-responsive">
                            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                <div>
                                    <div>
                                        <table class="table table-striped dataTable no-footer" id="DataTables_Table_0" role="grid">
                                            <thead>
                                                <tr role="row">
                                                    <th class="" tabindex="0" aria-controls="DataTables_Table_0"
                                                        rowspan="1" colspan="1" aria-label="Country or Region"
                                                        role="columnheader" scope="col">Country or Region</th>

                                                    <th class="text-right " tabindex="0" aria-controls="DataTables_Table_0"
                                                        rowspan="1" colspan="1" aria-label="Percent" role="columnheader"
                                                        scope="col">Percent</th>
                                                    <th class="text-right" tabindex="0" aria-controls="DataTables_Table_0"
                                                        rowspan="1" colspan="1" aria-sort="descending"
                                                        aria-label="Current Enrollment" role="columnheader"
                                                        scope="col">Active Students</th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    </div>

    <!-- Placed at the end of the document so the pages load faster -->
    <div id="footer-sock-push"></div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block script %}
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        var months = JSON.parse('{{ months|safe }}');
        var months_keys_sorted = Object.keys(months).sort();
        var last_month_key = months_keys_sorted[months_keys_sorted.length - 1];

        // Define JS global vars to work with external datamap.js file.
        var countries_list = months[last_month_key]['datamap_countries_list'];
    </script>
    <script src="{% static 'charts/slider.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/datamaps/0.5.8/datamaps.all.js"></script>
    <script src="{% static 'charts/vendored/datamaps.world.min.js' %}"></script>
    <script src="{% static 'charts/worldmap.js' %}"></script>
{% endblock %}